### ISSUE TITLE
Could not find driver

### ISSUE THREAD

**Issue by Meptinity** [Niall7459/NagarSite#2]
Uploaded, changed the old paths to the right paths, this is the only thing the website will show me: could not find driver

**Comment by Niall7459** [comment]
You need the php-pdo model.
You will need to do this using sudo apt-get install php7.0-mysql

**Comment by Niall7459** [comment]
Please be aware this is discontinued, there will probably be a lot of bugs or unfinished features.

**Comment by Meptinity** [comment]
Well, thank you. I just wonder what to do after i installed it? It seems like i have to create the database file (SQLSTATE[HY000] [2002] No such file or directory) but i'm not sure how to do that.

**Comment by Niall7459** [comment]
Run the sql code here

**Comment by Niall7459** [comment]
https://github.com/Niall7459/NagarSite/blob/master/DATABASE_SQL.SQL

**Comment by Meptinity** [comment]
Well i downloaded the file and uploaded it but i am getting the same error, thank you anyway.

**Comment by Niall7459** [comment]
The sql must be executed.

I do this through phoMyAdmin

**Comment by Meptinity** [comment]
Thank you very much but know it will show "SQLSTATE[HY000] [1045] Access denied for user 'ngnsite'@'localhost' (using password: YES)" 
Well, i am not advanced with SQL because i used .json before to store things

**Comment by Niall7459** [comment]
You need MySQL users setup

**Comment by Niall7459** [comment]
Create a user and edit the username and password in config.php
